BlogWebApplication/Controllers/ArticleController.cs
using BlogWebApplication.Helper;
using BlogWebApplication.Models;
using Core.Interfaces;
using Core.Model;
using System;
using BLL;
using System.Web;
using System.Web.Mvc;

namespace BlogWebApplication.Controllers
{
    public class ArticleController : Controller
    {
        private IArticleBUS _articleBUS;
        public ArticleController(IArticleBUS articleBUS)
        {
            this._articleBUS = articleBUS;
        }
        // GET: Article
        public ActionResult Index()
        {          
            return View();
        }

        // GET: Article
        public ActionResult Detail(string slug)
        {
            Article article = _articleBUS.GetArticleBySlug(slug);
            ViewBag.RandomArticle = _articleBUS.GetRandomArticleExceptOne(article);
            ViewBag.Comments = _articleBUS.GetAmountCommentByArticleId(article.Id);
            return View(article);
                     
        }

        [ChildActionOnly]
        public PartialViewResult GetReview(int ArticleId)
        {
            ViewBag.Comments = _articleBUS.GetAmountCommentByArticleId(ArticleId);
            return PartialView(_articleBUS.GetAllCommentByArticleId(ArticleId));
           
        }

        [ChildActionOnly]
        public PartialViewResult Review(int ArticleId)
        {
            ReviewViewModel ReviewVM = new ReviewViewModel()
            {
                ArticleId = ArticleId,
                UserId = UserHelper.GetCurrentUserId()
            };
            return PartialView(ReviewVM);           
        }

        [HttpPost]       
        public ActionResult Review(ReviewViewModel review)
        {
            Comment cmt = new Comment()
            {
                ArticleId = review.ArticleId,
                UserId = review.UserId,
                CreatedDate = DateTime.Now,
                Content = review.Content
            };
            //repo.Insert<Comment>(cmt);
            //repo.SaveChanges();
            ViewBag.CommentTotal = _articleBUS.GetAmountCommentByArticleId(review.ArticleId);
            string slug = _articleBUS.GetSlugByArticleId(review.ArticleId);
            return RedirectToAction("Detail",new { slug = slug });
            
        }
        [Authorize]
        public ActionResult NewArticle()
        {
            return View();
        }

        //[Authorize]
        //public ActionResult ListArticle()
        //{
        //   // int UserID = UserRepo.GetCurrentUserIDByUserName(UserHelper.GetCurrentUserName());
        //   // var ListArticle = _articleBUS.GetAllArticleByUserId(UserID, UserHelper.IsAdmin());
        //    return View("ListArticle", ListArticle);
        //}
        
        //[HttpPost]
        //[Authorize]
        //public ActionResult NewArticle(Article article, HttpPostedFileBase file)
        //{             
        //    Article NewArticle = new Article() ;
        //    NewArticle.Title = article.Title;
        //    NewArticle.Slug = article.Slug;
        //    NewArticle.Content = article.Content;
        //    NewArticle.CreatedDate = DateTime.Now;                     
        //    NewArticle.Owner = UserRepo.GetCurrentUserByUserName(UserHelper.GetCurrentUserName());
        //    repo.Insert<Article>(NewArticle);
        //    repo.SaveChanges();
        //    ImageHelper.SaveImage(NewArticle.Id, Server.MapPath("~"), file);
        //    return RedirectToAction("Detail", new { slug = NewArticle.Slug });            
        //}
        //[HttpPost]
        //[Authorize]
        //public ActionResult Remove(int Id)
        //{
        //    repo.Delete<Article>(repo.GetById<Article>(Id));
        //    repo.SaveChanges();
        //    return RedirectToAction("Article");
        //}
    }
}

BlogWebApplication/Controllers/HomeController.cs
using BlogWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Interfaces;
using Core.Model;
using BlogWebApplication.Helper;

namespace BlogWebApplication.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        private IRepository repo;
        public HomeController(IRepository repo)
        {
            this.repo = repo;
        }
        public ActionResult Index()
        {           
            var listArticle = repo.GetAll<Article>().OrderByDescending(a => a.CreatedDate).ToList();
            if (listArticle.Count == 0)
                return RedirectToAction("Login", "Account");
            Article NewestArrticle = listArticle.First();
            listArticle = listArticle.Skip(1).ToList();
            HomePageArticle model = new HomePageArticle() { Articles = listArticle, NewestArticle = NewestArrticle };
            return View(model);
        }
    }
}

BlogWebApplication/Views/Home/Index.cshtml
@using BlogWebApplication.Models
@using BlogWebApplication.Helper
@model HomePageArticle
@{
    ViewBag.Title = "Index";
}

<div class="container-fluid">

    <!--Section: Blog v.4-->
    <section class="section section-blog-fw">

        <!--First row-->
        <div class="row">
            <div class="col-md-12 wow fadeIn" data-wow-delay="0.2s">
                <!--Featured image-->
                <img src="~/imgs/@Model.NewestArticle.Id/main.jpg">

                <!--Post data-->
                <div class="jumbotron wow fadeIn" data-wow-delay="0.4s">
                    <h2><a href="@Url.Action("Detail","Article",new {slug = Model.NewestArticle.Slug })">@Model.NewestArticle.Title</a></h2>
                    <p>Written by <a>@Model.NewestArticle.Owner.FullName</a>, @Model.NewestArticle.CreatedDate.ToShortDateString()</p>

                    <!--Social shares-->
                    <div class="social-counters ">                       
                        <!--Comments-->
                        <a class="btn btn-default" href="@Url.Action("Detail","Article",new {slug = @Model.NewestArticle.Slug })">
                            <i class="fa fa-comments-o left "></i>
                            <span class="hidden-md-down ">Comments</span>
                        </a>
                        @*<span class="counter ">@.GetAmountCommentByArticle(Model.NewestArticle.Id)</span>*@

                    </div>
                    <!--/.Social shares-->

                </div>
                <!--/Post data-->
                <!--Excerpt-->
                <div class="excerpt wow fadeIn" data-wow-delay="0.4s">
                    <p>       
                        @Model.NewestArticle.Content.ConvertToLimitString(550)
                    </p>

                    
                </div>
            </div>
        </div>
        <!--/First row-->           
    </section>
    <!--/Section: Blog v.4-->

    <hr class="between-sections">
    

    <!--Section: Blog v.3-->
    <section class="section extra-margins">

        <!--Section heading-->
        <h1 class="section-heading wow fadeIn" data-wow-delay="0.2s">Blog listing</h1>
        <!--Section sescription-->
       
        @foreach (var a in Model.Articles)
        {           
            <div class="row">
                <!--First column-->
                <div class="col-md-5 mb-r wow fadeIn" data-wow-delay="0.3s">
                    <!--Featured image-->
                    <div class="view overlay hm-white-slight">
                        <img src="~/imgs/@a.Id/main.jpg">
                        <a>
                            <div class="mask"></div>
                        </a>
                    </div>
                </div>
                <!--/First column-->
                <!--Second column-->
                <div class="col-md-7 mb-r wow fadeIn" data-wow-delay="0.3s">
                    <!--Excerpt-->
                    <!--<h5 class="teal-text "><i class="fa fa-money "></i>Business</h5>-->
                    <h4>@a.Title</h4>
                    <p>@a.Content.ConvertToLimitString(300)</p>
                    <p>by <a><strong>@a.Owner.FullName</strong></a>, @a.CreatedDate.ToShortDateString()</p>                 
                    @Html.ActionLink( linkText:"Read more",actionName:"Detail",controllerName:"Article",routeValues:new { slug = a.Slug },
                                    htmlAttributes: new { @class="btn btn-primary" })
                </div>
                <!--/Second column-->

            </div>        
            <hr>
        }
                     
    </section>
    <!--/Section: Blog v.3-->

</div>